[versions]
elimuModel = "model-2.0.88"
elimuAnalytics = "3.1.28"
elimuProvider = "1.2.34"
elimuCommonutils = "1.0.5"
material = "1.5.0"
junit = "4.13.2"
flexbox = "3.0.0"
glide = "4.16.0"
hilt = "2.55"

constraintLayout = "2.1.3"
appCompat = "1.4.1"
androidXJunit = "1.1.3"
androidXEspresso = "3.4.0"
coreKtx = "1.15.0"
kotlinGradlePlugin = "2.1.0"
kotlinCoroutines = "1.10.2"
agp = "8.8.2"
grgit = "5.0.0"

[libraries]
elimu-model = { group = "com.github.elimu-ai", name = "model", version.ref = "elimuModel" }
elimu-analytics = { group = "com.github.elimu-ai", name = "analytics", version.ref = "elimuAnalytics" }
elimu-provider = { group = "com.github.elimu-ai", name = "content-provider", version.ref = "elimuProvider" }
elimu-common-utils = { group = "com.github.elimu-ai", name = "common-utils", version.ref = "elimuCommonutils" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
flexbox = { group = "com.google.android.flexbox", name = "flexbox", version.ref = "flexbox" }
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-android-plugin = { group = "com.google.dagger", name = "hilt-android-gradle-plugin", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
kotlin-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinCoroutines" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appCompat" }
androidx-constraint-layout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintLayout" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidXJunit" }
androidx-espresso = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidXEspresso" }

junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
android-gradle-plugin = { group = "com.android.tools.build", name = "gradle", version.ref = "agp"}
grgit = { group = "org.ajoberstar.grgit", name = "grgit-gradle", version.ref = "grgit"}
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlinGradlePlugin"}

[plugins]
